apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-app.fullname" . }}-config
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
