apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoplay
  labels:
    app: argoplay
spec:
  replicas: 2  # Runs two copies for high availability
  selector:
    matchLabels:
      app: argoplay
  template:
    metadata:
      labels:
        app: argoplay
    spec:
      containers:
        - name: argoplay-container
          image: lrehdocker/argoplay:v1  # Replace with your actual image
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"