apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-argoplay
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: my-app=lrehdocker/argoplay
    argocd-image-updater.argoproj.io/my-app.update-strategy: latest
    argocd-image-updater.argoproj.io/my-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/my-app.helm.image-tag: image.tag

spec:
  project: default
  source:
    repoURL: 'https://github.com/lreh/argoplay.git'
    targetRevision: HEAD
    path: charts/java-app
    helm:
      # You can point to different value files for different environments
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
