apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-argoplay
  namespace: argocd

spec:
  project: default
  source:
    repoURL: 'https://github.com/lreh/argoplay.git'
    targetRevision: HEAD
    path: charts/java-app
    helm:
      # You can point to different value files for different environments
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# Add this to your container spec in the deployment YAML
startupProbe:
  httpGet:
  port: 8080
  failureThreshold: 30  # 30 tries...
  periodSeconds: 10     # ...every 10 seconds = 300 seconds (5 mins) of boot time

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 90
  timeoutSeconds: 5      # Increased from 1s
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 60
  timeoutSeconds: 5      # Increased from 1s
  periodSeconds: 10

