apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-argoplay
  namespace: argocd

annotations:
    # 1. List the image to watch (alias=image_path)
    argocd-image-updater.argoproj.io/image-list: my-java-app=lrehdocker/argoplay
    
    # 2. Set the update strategy (semver, latest, or newest-build)
    argocd-image-updater.argoproj.io/my-java-app.update-strategy: latest
    
    # 3. CRITICAL: Map the tag update to your Helm values
    argocd-image-updater.argoproj.io/my-java-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/my-java-app.helm.image-tag: image.tag
    
    # 4. Choose how to save the change (argocd or git)
    argocd-image-updater.argoproj.io/write-back-method: argocd

spec:
  project: default
  source:
    repoURL: 'https://github.com/lreh/argoplay.git'
    targetRevision: HEAD
    path: charts/java-app
    helm:
      # You can point to different value files for different environments
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
